---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open-webui
spec:
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        env:
          - name: OLLAMA_BASE_URLS
            value: http://ollama:80
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: open-webui-data
          mountPath: /app/backend/data
  volumeClaimTemplates:
  - metadata:
      name: open-webui-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui
spec:
  type: LoadBalancer
  selector:
    app: open-webui
  ports:
  - port: 8080
    name: http
    targetPort: http
    protocol: TCP
